### ISSUE TITLE
Typo in AND card, police checks

### ISSUE THREAD

**Issue by Arjanvde** [jjtbsomhorst/eu.jeroensomhorst.anwb#1]
Hi,

Please note that there is wrong sentence in the AND card for the police checks.

In this case, there is a police check so the word NO should be removed.

![schermafbeelding 2016-10-29 om 11 00 21](https://cloud.githubusercontent.com/assets/17526110/19828489/02f5b9f6-9dc7-11e6-814d-85dc55f467aa.png)

Thanks
Arjan

**Comment by jjtbsomhorst** [comment]
Thanks for the update. I will fix this in a future release.

**Comment by jjtbsomhorst** [comment]
Fixed it in version 0.4.3. I have updated the repository. If you have the cli tools installed for homey you could test it yourself.

**Comment by Arjanvde** [comment]
Fixed, thanks!
