### ISSUE TITLE
Homey Flow not expected response

### ISSUE THREAD

**Issue by chrisboer** [jjtbsomhorst/eu.jeroensomhorst.anwb#2]
Flow 

"Trigger : Microfoon"         "en"                       "Uitvoer" 
Staat er file                     File : A6              File informatie : A6

Vervolgens file informatie van alle wegen.

**Comment by jjtbsomhorst** [comment]
Je hebt een flow gemaakt waarbij je in als trigger 'microfoon' hebt gebruikt met als tekst 'staat er file' en in de uitvoer dus files van de A6. Dan komt dat denk ik door dat je eenzelfde geluidstrigger hebt gemaakt als de trigger die al in de app zelf gesupport wordt. 

Vanuit de anwb app worden namelijk alle files opgedreund als je zegt 'staat er file' of 'staan er files'. Aangezien je dezelfde trigger hebt gebruikt voor jou flow conflicteren deze met elkaar. Als je in jou flow de tekst aanpast naar iets als 'staan er nog files' dat het dan goed gaat omdat er het woordje nog tussen staat.

**Comment by chrisboer** [comment]
Je hebt helemaal gelijk, heb het aangepast en nu werkt het.
